//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProdutosPOO.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProdutosPOO.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trabalho realizado no ambito da disciplina de Programação Orientada a Objectos.
        /// </summary>
        internal static string MESSAGE_ABOUT_DESCRICAO {
            get {
                return ResourceManager.GetString("MESSAGE_ABOUT_DESCRICAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sobre Nós.
        /// </summary>
        internal static string MESSAGE_ABOUT_FORM {
            get {
                return ResourceManager.GetString("MESSAGE_ABOUT_FORM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diogo André Teixeira Lucas.
        /// </summary>
        internal static string MESSAGE_ABOUT_NOME {
            get {
                return ResourceManager.GetString("MESSAGE_ABOUT_NOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número: a22000968.
        /// </summary>
        internal static string MESSAGE_ABOUT_NUMERO {
            get {
                return ResourceManager.GetString("MESSAGE_ABOUT_NUMERO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao eliminar [{0}].
        /// </summary>
        internal static string MESSAGE_ELIMINAR_ERRO {
            get {
                return ResourceManager.GetString("MESSAGE_ELIMINAR_ERRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        internal static string MESSAGE_ELIMINAR_INFO {
            get {
                return ResourceManager.GetString("MESSAGE_ELIMINAR_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja eliminar este produto?.
        /// </summary>
        internal static string MESSAGE_ELIMINAR_MSG {
            get {
                return ResourceManager.GetString("MESSAGE_ELIMINAR_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto eliminado com sucesso.
        /// </summary>
        internal static string MESSAGE_ELIMINAR_SUCESSO {
            get {
                return ResourceManager.GetString("MESSAGE_ELIMINAR_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de stock baixo, por favor, comunicar ao sector comercial..
        /// </summary>
        internal static string MESSAGE_ERRO_STOCKLABEL {
            get {
                return ResourceManager.GetString("MESSAGE_ERRO_STOCKLABEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao gravar [{0}].
        /// </summary>
        internal static string MESSAGE_GRAVAR_ERRO {
            get {
                return ResourceManager.GetString("MESSAGE_GRAVAR_ERRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravar.
        /// </summary>
        internal static string MESSAGE_GRAVAR_INFO {
            get {
                return ResourceManager.GetString("MESSAGE_GRAVAR_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja gravar este produto?.
        /// </summary>
        internal static string MESSAGE_GRAVAR_MSG {
            get {
                return ResourceManager.GetString("MESSAGE_GRAVAR_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produto gravado com sucesso.
        /// </summary>
        internal static string MESSAGE_GRAVAR_SUCESSO {
            get {
                return ResourceManager.GetString("MESSAGE_GRAVAR_SUCESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existe nenhum produto com este ID.
        /// </summary>
        internal static string MESSAGE_ID_NA {
            get {
                return ResourceManager.GetString("MESSAGE_ID_NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A descrição têm que estar preenchida.
        /// </summary>
        internal static string MESSAGE_V_DESCRICAO_INVALIDO {
            get {
                return ResourceManager.GetString("MESSAGE_V_DESCRICAO_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O ID têm que estar preenchido e ser numerico.
        /// </summary>
        internal static string MESSAGE_V_ID_INVALIDO {
            get {
                return ResourceManager.GetString("MESSAGE_V_ID_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap newlogo {
            get {
                object obj = ResourceManager.GetObject("newlogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
